# Generated by Django 3.2.18 on 2023-03-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'COD'), ('MOMO', 'MOMO')], max_length=15),
        ),
    ]
